//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstSession.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public int ID { get; set; }
        public Nullable<int> uID { get; set; }
        public Nullable<int> enrollmentID { get; set; }
        public Nullable<int> A1_Max { get; set; }
        public Nullable<double> A1_Obt { get; set; }
        public Nullable<int> A2_Max { get; set; }
        public Nullable<double> A2_Obt { get; set; }
        public Nullable<int> A3_Max { get; set; }
        public Nullable<double> A3_Obt { get; set; }
        public Nullable<int> A4_Max { get; set; }
        public Nullable<double> A4_Obt { get; set; }
        public Nullable<int> A5_Max { get; set; }
        public Nullable<double> A5_Obt { get; set; }
        public Nullable<int> Q1_Max { get; set; }
        public Nullable<double> Q1_Obt { get; set; }
        public Nullable<int> Q2_Max { get; set; }
        public Nullable<double> Q2_Obt { get; set; }
        public Nullable<int> Q3_Max { get; set; }
        public Nullable<double> Q3_Obt { get; set; }
        public Nullable<int> Mid_Max { get; set; }
        public Nullable<double> Mid_Obt { get; set; }
        public Nullable<int> SendUp_Max { get; set; }
        public Nullable<double> SendUp_Obt { get; set; }
        public Nullable<int> Final_Max { get; set; }
        public Nullable<double> Final_Obt { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual User User { get; set; }
    }
}
