//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstSession.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorCours
    {
        public int ID { get; set; }
        public int sectionID { get; set; }
        public Nullable<int> instructorID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> uID { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
    }
}
