//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTTIMS_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorCours
    {
        public InstructorCours()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int ID { get; set; }
        public string ClassRoom { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Room { get; set; }
        public Nullable<int> uID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
    }
}
