//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTTIMS_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Assessments = new HashSet<Assessment>();
            this.Attendences = new HashSet<Attendence>();
            this.Batches = new HashSet<Batch>();
            this.Courses = new HashSet<Course>();
            this.Departments = new HashSet<Department>();
            this.Enrollments = new HashSet<Enrollment>();
            this.Instructors = new HashSet<Instructor>();
            this.Instructors1 = new HashSet<Instructor>();
            this.InstructorCourses = new HashSet<InstructorCours>();
            this.Sections = new HashSet<Section>();
            this.Students = new HashSet<Student>();
            this.Students1 = new HashSet<Student>();
        }
    
        public int UID { get; set; }
        public string UserName { get; set; }
        public string UPassword { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> LastAccessedOn { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Instructor> Instructors { get; set; }
        public virtual ICollection<Instructor> Instructors1 { get; set; }
        public virtual ICollection<InstructorCours> InstructorCourses { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Student> Students1 { get; set; }
    }
}
